# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    name: Build and deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.14.x'

    - name: Run npm install
      working-directory: frontend
      run: npm install
      
    - name: Run npm install
      working-directory: backend
      run: npm install

    - name: Run cli packages
      working-directory: frontend
      run: npm install -g @angular/cli

    - name: Run Build
      working-directory: frontend
      run: ng build
      
    - name: Run Build
      working-directory: backend
      run: npm build --if-present
